### ISSUE TITLE
Dockerfileについて質問

### ISSUE THREAD

**Issue by smellman** [amx-project/mojxml2geojson#3]
- ubuntu:latestを使っているがlatestが次のものになると依存性が壊れる可能性があるのでjammyを直接指定した方がよさそう
- tippicanoeをインストールしているが、そもそもentrypoint.shでmojxml2geojsonのみ使われるようになっているため、tippicanoeのインストールは削除した方が良いのでは無いか？
    - 軽めのイメージにするならpythonの公式イメージを採用するなど

**Comment by keichan34** [comment]
ああ、すみません。実験用にtippecanoe入れてましたがおっしゃる通りこれ単体ではいらないですね。
pythonベースに移行するのは賛成

**Comment by smellman** [comment]
クローズします。
